config/routes.rb
DealHound::Application.routes.draw do

  root :to => 'commodities#index'
  controller :subscriptions do
    post 'subscription'
    get 'unsubscribe'
  end
  resources :commodities do
    member do
      get 'delete_img' => :del_image
    end
  end

  resources :deals do
    collection do
      post 'index'
      get 'show_commodities'
    end
  end
  resources :admins
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :delete
  end
  controller :categories do
    post 'edit_delete'
  end

  resources :users do
    member do
      get :edit_password
      put :save_password
      put :save_after_forget
    end
    collection do
      post :forget_password
      get :change_password
    end
  end
  resources :categories do
    resources :commodities, :only => [:index]
  end

  resources :vouchers
  resources :carts
  resources :line_items
  resources :orders

    

    

      

    

  

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :mobile_no, :name, :wallet, :admin, :password, :password_confirmation, :user_name, :authenticate_link

  has_secure_password
  
  #Validation

  validates :user_name, :email, :presence => true
  validates :password, :on => :create, :presence => true
  validates :user_name, :allow_blank => true, 
                        :format => { with: /[A-z][A-z0-9]*([-_.][A-z0-9])*/, 
                                     message: "Invalid format" }, 
                        :uniqueness => { :case_sensitive => false }
  validates :email, :allow_blank => true, 
                    :format => {
                      with: /(^[A-z0-9]+((.[A-z0-9]+)|(-[A-z0-9]+)|(_[A-z0-9]+)|([A-z0-9]+))*@[A-z0-9]{3,}.[A-z]{2,4}(.[A-z]{2})?)$/, 
                      message: "invalid email address"
                    }, 
                    :uniqueness => true
  validates :mobile_no, :numericality => { greater_than_or_equal_to: 0, 
                                           :only_integer => true, 
                                           message: 'must be a valid mobile'}, 
                        :allow_blank => true
  validates :password, :if => :password, 
                       :presence => true, 
                       :length => { :within => 8..20},
                       :confirmation => { :message => "Password does not match" }
  validates :wallet, :allow_blank => true, 
                     :numericality => { greater_than_or_equal_to: 0, 
                                        message: 'must be a valid price'}

  # Associations

  has_one :cart, :dependent => :destroy
  has_many :orders

  # Callbacks
  before_validation :strip_whitespace!, :only => [:name, :email, :user_name]

  # Scopes
  scope :main_admin, where('user_name = "a" AND admin = 1')

  def strip_whitespace! 
    self.name.strip!
    self.user_name.strip!
    self.email.strip!
  end

  def self.search(search, user)
    if search
      search_pattern = "%#{search}%"
      where('user_name != ? AND ((name LIKE ?) OR (id like ?) OR (email LIKE ?) OR (wallet > ?)) ', user.user_name, search_pattern, search_pattern, search_pattern, search)
    else
      scoped
    end
  end

  def update_password(params)
    update_attributes(:password => params[:user][:password], :password_confirmation => params[:user][:password_confirmation], :authenticate_link => nil)
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  helper_method :sort_column, :sort_direction
  
  before_filter(:except => [:new, :create, :forget_password, :change_password, :save_after_forget]) { |conroller| conroller.authorize(false) }
  before_filter(:only => [:index, :destroy]) { |conroller| conroller.authorize(true) }

  def index
    @user = User.find(session[:user_id])
    @users = User.search(params[:search], @user).order(sort_column + " " + sort_direction).paginate page: params[:page], per_page: 10
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find_by_id(params[:id])
    if @user.nil?
      flash[:error] = "Invalid user"
      redirect_to users_url
    elsif authorize @user.id
      true
    end
  end

  def edit_password
    @user = User.find params[:id]
  end

  def save_password
    @user = User.find_by_id session[:user_id]
    if @user && @user.authenticate(params[:old_password]) && @user.update_password(params)
        redirect_to commodities_url, notice: "#{@user.name}, your password has been updated."
    else
      flash[:error] = "Invalid Current Password" unless @user.errors.any?
      render :edit_password
    end
  end

  def change_password
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate_link == params[:authenticate_link]
      flash[:notice] = "Please enter new password"
    else
      flash[:error] = "Invalid request"
      redirect_to login_url
    end
  end

  def save_after_forget
    @user = User.find(params[:id])
    if @user.update_password(params)
      create_session(@user)
      redirect_to commodities_url, notice: "Password changed"
    else
      render :change_password
    end
  end

  def forget_password
    @user = User.find_by_email(params[:email])
    if @user
      authenticate_link = BCrypt::Password.create("tutu")
      @user.update_attribute(:authenticate_link, authenticate_link)
      authentication_path = change_password_users_url + "?email=#{@user.email}&authenticate_link=" + authenticate_link
      PasswordNotifier.reset_password(@user, authentication_path).deliver
      flash.now[:forget_password] = "Authentication link has been sent to your email. Please check it."
    else
      flash.now[:forget_password] = "Email is not registered."
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @user = User.find(params[:id])
    usr = User.find(session[:user_id])
    paramss = wallet_condition usr, @user, params
    nxt_page = usr.admin ? users_url : commodities_url
    if @user.update_attributes!(paramss[:user])
      redirect_to nxt_page, notice: "#{@user.name}'s profile has been updated."
    else
      render :edit
    end
  end

  def wallet_condition(usr, user, params)
    if !usr.admin && !params[:user][:wallet].nil? && usr.id == user.id
      params[:user].delete(:wallet)
      logger.info("#{usr.id} a.k.a. #{usr.name} has tried to access his wallet by unfair means.")
    end
    params
  end

  def create
    params[:user][:wallet] = 0
    @user = User.new(params[:user])
    if @user.save
      create_session(@user)
      redirect_to commodities_url, notice: "Welcome #{params[:name]}"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to request.referrer
  end

  private

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:class => "form-horizontal"}) do |f| %>
  <fieldset id = "signup">
    <legend>Please Enter Details</legend>
    <br> <div class="control-group">
   <%= f.label :user_name, 'Username', :class => "control-label" %>
   <div class="controls">
     <% if @user.new_record? %>
        <%= f.text_field :user_name, :placeholder => 'Username' %>
      <% else %>
        <%= @user.user_name %>
      <% end %>
   </div>
 </div>
<% if @user.new_record? %>
 <div class="control-group">
   <%= f.label :password, :class => "control-label" %>
   <div class="controls">
     <%= f.password_field :password, :placeholder => 'Password' %>
   </div>
 </div>
 <div class="control-group">
   <%= f.label :password_confirmation, 'Confirm Password', :class => "control-label" %>
   <div class="controls">
      <%= f.password_field :password_confirmation, :placeholder => 'Confirm Password' %>
   </div>
 </div>
 <% end %>
 <div class="control-group">
   <%= f.label :name, :class => 'control-label' %>
   <div class="controls">
     <%= f.text_field :name, :placeholder => 'First Name', size: 20 %>
   </div>
 </div>
 <div class="control-group">
   <%= f.label :email, :class => 'control-label' %>
   <div class="controls">
     <%= f.text_field :email, :placeholder => 'Email', size: 20 %>
   </div>
 </div>
 <div class="control-group">
   <%= f.label :mobile_no, :class => 'control-label' %>
   <div class="controls">
     <%= f.text_field :mobile_no, :placeholder => 'Mobile Number', size: 20 %>
   </div>
 </div>
 <div class="control-group">
   <%= f.label :wallet, :class => 'control-label' %>
   <div class="controls">
    <% if find_user && !(@user.admin) && find_user.admin %>
      &#8377; <%= f.text_field :wallet, :placeholder => 'Mobile Number', size: 20 %>
  <% else %>
    <%= number_to_currency(@user.wallet, :unit => '&#8377; ') %>
  <% end %>
   </div>
 </div>
   <div class="control-group">
     <div class="controls">
       <%= f.submit :class => 'btn' %>
     </div>
   </div>
  </fieldset>
<% end %>

app/views/users/_users.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class = "general">
  <tr>
    <td colspan = 7><h2>Users</h2></td>
  </tr>
  <tr>
    <th><%= sortable "id", 'Reg. no.' %></th>
    <th><%= sortable "name" %></th>
    <th><%= sortable "user_name" %></th>
    <th>Email</th>
    <th>Mobile</th>
    <th><%= sortable "wallet" %></th>    
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%=user.user_name %></td>
    <td><%=user.email %></td>
    <td><%=user.mobile_no %></td>
    <td><%= number_to_currency(user.wallet, :unit => '&#8377; ') %></td>
    <td>
      <%= link_to 'Edit', edit_user_url(user) %>/<%= link_to 'Delete', user, :method => :delete, data: {confirm: "Are you sure?" } %>
    </td>
  </tr>
  <% end %>
</table>
<p class = "paginate_p"><%= will_paginate @orders %></p>

app/views/users/change_password.html.erb
<% form_for @user do |f| %>
  Old Password <%= f.text_field%>
  New Password <%= f.text_field :password %>
  Confirm Password <%= f.text_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/edit_password.html.erb
<fieldset id = "change_password">
  <legend>Change Password</legend>
  <table>
    <%= form_for @user, :url => save_password_user_path(@user) do |f| %>
      <tr>
        <td>
          Current Password 
        </td>
        <td>
          <%= password_field_tag :old_password %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label :password, 'New Password' %>
        </td>
        <td>
          <%= f.password_field :password, :size => 40 %>
        </td>
        <td>
          <% if @user.errors.get(:password) %>
              <div class = "field_with_errors"><%= @user.errors.get(:password).first %></div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          Confirm Password
        </td>
        <td>
         <%= f.password_field :password_confirmation, :size => 40 %>
       </td>
     </tr>
     <tr>
      <td></td>
      <td>
        <%= f.submit %>
      </td>    
    <% end %>
  </table>
</fieldset>

app/views/users/forget_password.js.erb
console.log("hello")
$('#forget_password_tr').html("<%= escape_javascript(render('/sessions/forget_password')) %>")

app/views/users/index.html.erb
<%= form_tag users_path, :method => :get, :class => "search_ajax" do %>
  <p class = "search_p">
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div class = "sort_paginate_ajax"><%= render 'users' %></div>
<% end %>

app/views/users/index.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("users")) %>")