config/routes.rb
DealHound::Application.routes.draw do

  root :to => 'commodities#index'
  controller :subscriptions do
    post 'subscription'
    get 'unsubscribe'
  end
  resources :commodities do
    member do
      get 'delete_img' => :del_image
    end
  end

  resources :deals do
    collection do
      post 'index'
      get 'show_commodities'
    end
  end
  resources :admins
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :delete
  end
  controller :categories do
    post 'edit_delete'
  end

  resources :users do
    member do
      get :edit_password
      put :save_password
      put :save_after_forget
    end
    collection do
      post :forget_password
      get :change_password
    end
  end
  resources :categories do
    resources :commodities, :only => [:index]
  end

  resources :vouchers
  resources :carts
  resources :line_items
  resources :orders

    

    

      

    

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :user_id

  belongs_to :user
  has_many :line_items, :as => :item, :dependent => :destroy

  def add_item(p_and_s, quantity = 1)

    if p_and_s[:type] === "Voucher"
      @p_and_s = Voucher.find(p_and_s[:id])
      li_added_message = "(#{@p_and_s.title})"
    else
      @p_and_s = CommoditySku.find(p_and_s[:id])
      li_added_message =  " (#{@p_and_s.color} #{@p_and_s.size})"
    end
    li_added_message = "#{@p_and_s.commodity.title}" + li_added_message
    cart_lis = line_items.select('id')
    current_item = @p_and_s.line_items.where('deal_id is null').find_by_id(cart_lis)
    li_with_deal = @p_and_s.line_items.where('deal_id is not null').find_by_id(cart_lis)
    deal = @p_and_s.deals.where('visible = ?', true).first
    without_deal_quantity = quantity - deal.remaining_quantity if deal
    if current_item && !deal
      current_item.quantity = quantity
    elsif li_with_deal && deal
        current_item, li_with_deal = utility(without_deal_quantity, current_item, line_items, @p_and_s, li_with_deal, quantity, deal)
    elsif deal
        li_with_deal = @p_and_s.line_items.build()
        li_with_deal.item = self
        li_with_deal.deal = deal
        current_item, li_with_deal = utility(without_deal_quantity, current_item, line_items, @p_and_s, li_with_deal, quantity, deal)
        li_with_deal.price = (1-(deal.discount/100)) * @p_and_s.selling_price
    else
        current_item = line_items.build()
        current_item.p_and_s = @p_and_s
        current_item.price = @p_and_s.selling_price
        current_item.quantity = quantity
    end
    li_added_message = "#{quantity} item(s) 0f " + li_added_message + " has/have been added.1"
    [current_item, li_with_deal, li_added_message]
  end

  def utility(without_deal_quantity, current_item, line_items, p_and_s, li_with_deal, quantity, deal)
    if without_deal_quantity > 0 
      if current_item
        current_item.quantity = without_deal_quantity
      else
        current_item = line_items.build()
        current_item.p_and_s = p_and_s
        current_item.price = p_and_s.selling_price
        current_item.quantity = without_deal_quantity
      end
      li_with_deal.quantity = deal.remaining_quantity
    else
      li_with_deal.quantity = quantity
    end
    [current_item, li_with_deal]
  end

  def items_available
    availability = true
    items_not_available = []
    line_items.each do |li|
      if li.deal && (!(li.deal.visible) || li.deal.remaining_quantity < li.quantity)
        availability = false
        li.destroy
        items_not_available << "#{li.p_and_s.commodity.title.to_s}(with -deal)"
      elsif li.quantity > li.p_and_s.quantity
        availability = false
        li.update_attribute(:quantity, li.p_and_s.quantity)
        items_not_available << li.p_and_s.commodity.title
      end
    end
    [availability, items_not_available]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_filter { |conroller| conroller.authorize(session[:admin]) }
  
  def show
      @cart = Cart.find_by_id(params[:id])
    if @cart
      respond_to do |format|
        flash[:cart_flash] = true
        flash[:item_info] = flash[:item]
        format.html { redirect_to request.referrer }
      end
    else      
      flash[:error] = "Invalid cart option"
      redirect_to login_url
    end    
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= link_to '', "", :remote => true, :onclick => 'hide_cart()', :id => "close_cart" %>
<% @cart = User.find(session[:user_id]).cart %>
<h2>My Cart(<%= @cart.line_items.count %>)</h2>
<% if flash[:item_info] %>
<div id = "flash_message">
  <% if flash[:item_info].to_s.last === "1" %>
  <div class = "green_div">
  <% else %>
  <div class = "red_div">
  <% end %>
    <%= flash[:item_info].to_s.chop %>
  </div>
</div>
<% end %>
<% if @cart.line_items.any? %>
<div id = "scroll_cart">
  <table id = "cart_table">
    <tr>
      <td></td>
      <td>Item</td>
      <td>Price</td>
      <td>Quantity</td>
      <td>Sub Total</td>
      <td></td>
    </tr>
    <% @cart.line_items.each do |item| %>
      <tr>
        <% commodity = item.p_and_s.commodity %>
        <% p_and_s = item.p_and_s %>
        <td>
          <% if commodity.images[0] %>
            <%= image_tag commodity.images[0].photo.url(:very_small) %>
          <% end %>
        </td>
        <td>
          <%= commodity.title.capitalize %> (
          <% if p_and_s.class.to_s == "Voucher" %>
          <%= p_and_s.title %>
          <% elsif p_and_s.class.to_s == "CommoditySku" %>
          <%= p_and_s.size %> <%= p_and_s.color %>
          <% end %>
          )
          <% if item.deal_id %>
          -with Deal
          <% end %>
        </td>
        <td><%= number_to_currency(item.price, :unit => '&#8377;') %></td>
        <td>
          <%= form_tag line_items_path(:p_and_s => { :id => p_and_s.id, :type => p_and_s.class.to_s}) do %>
            <%= select_tag :quantity, options_for_select((1..p_and_s.quantity).to_a, item.quantity), :onchange => 'quantity_changed(this)', :remote => true %>
            <%= submit_tag '', :class => "update_quantity_button" %>
          <% end %>
        </td>
        <td><%= number_to_currency(item.total_price, :unit => '&#8377; ') %></td>
        <td><%= link_to '', item, :method => :delete, :remote => true, :class => 'delete_item' %></td>
      </tr>
    <% end %>
    <tr>
  </table>
</div>
<div id = "cart_footer">
  <span id = "tot_price"> Total Price: <b><%= number_to_currency(@cart.total_price, :unit => '&#8377;') %></b></span><br><br>
  <%= link_to 'Proceed to Payment', new_order_url %>
  <%= link_to 'Add more item(s) to cart', "", :remote => true, :onclick => 'hide_cart()' %>
</div>
<% else %>
  <p id = "no_item_p"><br><%= image_tag '/assets/empty-cart.jpg' %><br>There is no item in Cart right now.<br><br></p>
  <%= link_to 'Proceed to shopping', "", :remote => true, :onclick => 'hide_cart()', :id => "pro_to_shop" %>
<% end %>
<% if flash[:cart_flash] %>
  <script type="text/javascript">show_cart_with_flash()</script>
<% end %>

app/views/carts/_show.html.erb
<%= link_to '', "", :remote => true, :onclick => 'hide_cart()', :id => "close_cart" %>
<% @cart = User.find(session[:user_id]).cart %>
<h2>My Cart(<%= @cart.line_items.count %>)</h2>
<% if flash[:item_info] %>
<div id = "flash_message">
  <% if flash[:item_info].to_s.last === "1" %>
  <div class = "green_div">
  <% else %>
  <div class = "red_div">
  <% end %>
    <%= flash[:item_info].to_s.chop %>
  </div>
</div>
<% end %>
<% if @cart.line_items.any? %>
<div id = "scroll_cart">
  <table id = "cart_table">
    <tr>
      <td></td>
      <td>Item</td>
      <td>Price</td>
      <td>Quantity</td>
      <td>Sub Total</td>
      <td></td>
    </tr>
    <% @cart.line_items.each do |item| %>
      <tr>
        <% commodity = item.p_and_s.commodity %>
        <% commodity_sku = item.p_and_s %>
        <td>
          <% if commodity.images[0] %>
            <%= image_tag commodity.images[0].photo.url(:very_small) %>
          <% end %>
        </td>
        <td><%= commodity.title.capitalize %> (<%= commodity_sku.size %> <%= commodity_sku.color %>)</td>
        <td><%= number_to_currency(commodity.selling_price, :unit => '&#8377;') %></td>
        <td>
          <%= form_tag line_items_path(commodity_sku_id: commodity_sku) do %>
            <%= select_tag :quantity, options_for_select((1..commodity_sku.quantity).to_a, item.quantity), :onchange => 'quantity_changed(this)', :remote => true %>
            <%= submit_tag '', :class => "update_quantity_button" %>
          <% end %>
        </td>
        <td><%= number_to_currency(item.total_price, :unit => '&#8377; ') %></td>
        <td><%= link_to '', item, :method => :delete, :remote => true, :class => 'delete_item' %></td>
      </tr>
    <% end %>
    <tr>
  </table>
</div>
<div id = "cart_footer">
  <span id = "tot_price"> Total Price: <b><%= number_to_currency(@cart.total_price, :unit => '&#8377;') %></b></span><br><br>
  <%= link_to 'Proceed to Payment', "", :remote => true, :onclick => 'hide_cart()' %>
  <%= link_to 'Add more item(s) to cart', "", :remote => true, :onclick => 'hide_cart()' %>
</div>
<% else %>
  <p id = "no_item_p"><br><%= image_tag '/assets/empty-cart.jpg' %><br>There is no item in Cart right now.<br><br></p>
  <%= link_to 'Proceed to shopping', "", :remote => true, :onclick => 'hide_cart()', :id => "pro_to_shop" %>
<% end %>
<% if flash[:cart_flash] %>
  <script type="text/javascript">show_cart_with_flash()</script>
<% end %>

app/views/carts/show.html.erb
<%= render 'carts/form' %>