config/routes.rb
DealHound::Application.routes.draw do

  root :to => 'commodities#index'
  controller :subscriptions do
    post 'subscription'
    get 'unsubscribe'
  end
  resources :commodities do
    member do
      get 'delete_img' => :del_image
    end
  end

  resources :deals do
    collection do
      post 'index'
      get 'show_commodities'
    end
  end
  resources :admins
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :delete
  end
  controller :categories do
    post 'edit_delete'
  end

  resources :users do
    member do
      get :edit_password
      put :save_password
      put :save_after_forget
    end
    collection do
      post :forget_password
      get :change_password
    end
  end
  resources :categories do
    resources :commodities, :only => [:index]
  end

  resources :vouchers
  resources :carts
  resources :line_items
  resources :orders

    

    

      

    

  

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  
  # attr_accessible :commodity_id, :discount, :p_and_s :end_date, :max_users, :start_date, :visible
  attr_protected :none

  # Validation
  validates :discount, :numericality => true

  validates :max_quantity, :allow_blank => true,  
                           :numericality => { greater_than_or_equal_to: 0, 
                                          :only_integer => true, 
                                          :message => "Enter a valid quantity"}

  validates :start_date, :presence => { :message => "Start date can't be blank." }
  validates :start_date, :date => { :before => :end_date }, 
                         :unless => proc { |deal| deal.start_date.blank? }
  
  validates :end_date, :presence => { :message => "End date can't be blank."}
  validates :end_date, :date => { :after => :end_date }, 
                       :unless => proc { |deal| deal.end_date.blank? }

  validate :validate_date_with_others
  
  # Callbacks
  before_save :check_visibility
  
  # Product and Services Association
  belongs_to :p_and_s, :polymorphic => true
  
  # Line Items Associations
  has_many :line_items

  # Instance Methods
  def validate_date_with_others
    p_and_s = self.p_and_s
    other_deals = p_and_s.deals if p_and_s # p_and_s.try(:deals)
    other_deals = other_deals.where('id != ?', self.id) if self.id
    if other_deals
      other_deals.each do |deal|
        if ((self.start_date <= deal.start_date && self.end_date  >= deal.start_date) || (deal.start_date <= self.start_date && deal.end_date >= self.start_date)) && deal != self
          self.errors.add(:start_date, "There has been already a deal in this duration. #{deal.start_date} - #{deal.end_date}")
        end
      end
    end
  end

  def self.search(search)
      where('city = ? AND visible = "true"',search)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
  end

  def show_commodities
    @products = CommoditySku.all
    @vouchers = Voucher.all
  end

  def new
    if params[:voucher] === "1"
      @commodity = Voucher.find(params[:vouchers])
    else params[:voucher] === "0"
      @commodity = CommoditySku.find(params[:products])
    end
    @deal = Deal.new
    @deal.p_and_s = @commodity
    flash.now[:notice] = "You have selected #{@deal.p_and_s.commodity.title}."
  end

  def create
    @deal = Deal.new(params[:deal])
    @deal.remaining_quantity = @deal.max_quantity
    if @deal.save
      redirect_to show_commodities_deals_url, notice: "Deal created successfully."
    else
      render :new
    end
  end

  def index
    @deals = Deal.search(params[:city])
    session[:city] = params[:city]
  end

  def show
    @deal = Deal.find_by_id(params[:id])
    redirect_to deals_path if @deal.nil?
  end

  def edit
    @deal = Deal.find(params[:id])
  end

  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy
    redirect_to deals_path
  end

  def update
    @deal = Deal.find(params[:id])
    params[:deal][:max_quantity] = @deal.max_quantity + params[:deal][:remaining_quantity].to_i - @deal.remaining_quantity
    if @deal.update_attributes(params[:deal])
      redirect_to deals_url(:city => @deal.city), notice: "Deal updated successfully."
    else
      render :edit
    end
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<fieldset>
  <legend>New deal</legend>
  <%= form_for @deal do |f| %>
  <table>
    <tr>
      <%= f.hidden_field :p_and_s_id %>
      <%= f.hidden_field :p_and_s_type %>
    </tr>
    <tr>
      <td>
        City*
      </td>
      <td>
        <%= f.text_field :city %>
        <% if @deal.errors.get(:city) %>
          <div class = "field_with_errors"><%= @deal.errors.get(:city).first %></div>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        Start Date
      </td>
      <td>
        <%= f.text_field :start_date, :readonly => true %>
        <% if @deal.errors.get(:start_date) %>
          <div class = "field_with_errors"><%= @deal.errors.get(:start_date).first %></div>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        End Date
      </td>
      <td>
        <%= f.text_field :end_date, :readonly => true %>
        <% if @deal.errors.get(:end_date) %>
          <div class = "field_with_errors"><%= @deal.errors.get(:end_date).first %></div>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        Discount
      </td>
      <td>
        <%= f.text_field :discount %>%
        <% if @deal.errors.get(:discount) %>
          <div class = "field_with_errors"><%= @deal.errors.get(:discount).first %></div>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        Max Quantity
      </td>
      <td>
        <% unless @deal.remaining_quantity %>
          <%= f.number_field :max_quantity %>
          <% if @deal.errors.get(:max_quantity) %>
            <div class = "field_with_errors"><%= @deal.errors.get(:max_quantity).first %></div>
          <% end %>
        <% else %>
          <%= f.label @deal.max_quantity %>
        <% end %>
      </td>
    </tr>
    <tr>
      <% if @deal.remaining_quantity %>
      <td>
        Remaining quantity
      </td>
      <td>
        <%= f.number_field :remaining_quantity %>
        <% if @deal.errors.get(:remaining_quantity) %>
          <div class = "field_with_errors"><%= @deal.errors.get(:remaining_quantity).first %></div>
        <% end %>
      </td>
      <% end %>
    </tr>
    <tr>
      <td>
      </td>
      <td>
        <%= f.submit %>
      </td>
    </tr>
  </table>
  <% end %>
</fieldset>


<link type="text/css" href="/assets/jquery-ui-1.8.23.custom.css" rel="stylesheet" />
<script type="text/javascript" src="/assets/jquery-1.8.0.min.js"></script>
<script type="text/javascript" src="/assets/jquery-ui-1.8.23.custom.min.js"></script>
<script type="text/javascript">
$("#deal_start_date").datepicker({dateFormat : 'dd/mm/yy', minDate: 0, numberOfMonths: 1, changeMonth: true, changeYear: true});
$("#deal_end_date").datepicker({dateFormat : 'dd/mm/yy', minDate: 0, numberOfMonths: 1, changeMonth: true, changeYear: true});
$("#product_tentative_selling_on").datepicker({dateFormat : 'dd/mm/yy', minDate: 0, numberOfMonths: 1, changeMonth: true, changeYear: true});
</script>

app/views/deals/_timer.html.erb
<%= sku.deal.end_date.to_time - Time.now %>

app/views/deals/edit.html.erb
<%= render 'form' %>

app/views/deals/index.html.erb
<fieldset>
  <legend>All deals</legend>
  <% if @deals.any? %>
    <% user = find_user %>
    <table>
      <tr>
        <th>Deal id</th>
        <th></th>
        <th>Category</th>
        <th>Discount</th>
        <th>Duration</th>
      </tr>
      <% @deals.each do |deal| %>
      <tr>
        <td>
          <%= deal.id %>
        </td>
        <td>
      <div>
        <%= image_tag deal.p_and_s.commodity.images[0].photo.url(:small) %>
      </div>

        </td>
        <td>
          <%= deal.p_and_s.commodity.category.name %><br>
          <%= deal.p_and_s.commodity.title %><br>
          <%= deal.p_and_s.class.to_s %>
        </td>
        <td>
          Price: &#8377;<%= price = deal.p_and_s.selling_price %><br>
          <b>Discount: <%= deal.discount %>%<br>
             New Price: &#8377; <%= (1-(deal.discount/100)) * price %>
           </b>
        </td>
        <td>
          <%= deal.start_date.day %>/<%= deal.start_date.month %>/<%= deal.start_date.year %> - 
          <%= deal.end_date.day %>/<%= deal.end_date.month %>//<%= deal.end_date.year %>
        </td>
        <td>
          
        </td>
        <td>
          <% if user && user.admin %>
            <%= link_to 'Edit', edit_deal_url(deal) %>
            <%= link_to 'Delete', deal, :method => :delete, data: {confirm: "Are you sure?" } %>
          <% end %>
        </td>
        <td><%= link_to 'Show', deal_url(deal) %>
        </td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <h4>Some great offers are coming soon.</h4>
  <% end %>
</fieldset>

app/views/deals/new.html.erb
<%= render 'form' %>

app/views/deals/show.html.erb
<fieldset>
  <legend><h2 id = "show_page"><%= @deal.p_and_s.commodity.title %></h2> - <%= @deal.p_and_s.class.to_s %></legend>
  <% @commodity = @deal.p_and_s.commodity %> 
  <%= render :template => '/commodities/show' %>
</fieldset>

app/views/deals/show_commodities.html.erb
<%= form_tag new_deal_url, :method => :get do %>
<fieldset>
  <legend>Select a product/service</legend>
<%= select_tag :voucher, options_for_select({ "Products" => "0", "Services" => "1"}), :onchange => "show_commodity(this)" %>
<%= submit_tag 'Go to Deal Details' %>
<br>
<br>
<div id = "Products">
  <table>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Size</th>
      <th>Color</th>
      <th>Quantity</th>
      <th>Selling Price</th>
      <th></th>
    </tr>
    <% @products.each do |product| %>
    <tr>
      <td>
        <%= radio_button_tag :products, product.id, true %>
      </td>
      <td>
        <%= product.id %>
        <%= product.commodity.title %>
      </td>
      <td>
        <%= product.size %>
      </td>
      <td>
        <%= product.color %>
      </td>
      <td>
        <%= product.quantity %>
      </td>
      <td>
        <%= product.selling_price %>
      </td>
    </tr>
    <% end %>
  </table>
</div>
<div id = "Services">
  <table>
    <tr>
      <th></th>
      <th>Service</th>
      <th>Price</th>
      <th>Discount</th>
    </tr>
    <% @vouchers.each do |voucher| %>
    <tr>
      <td>
        <%= radio_button_tag :vouchers, voucher.id, true %>
      </td>
      <td>
        <%= voucher.commodity.title %>
      </td>
      <td>
        <%= voucher.selling_price %>
      </td>
      <td>
        <%= voucher.discount %>%
      </td>
    </tr>
    <% end %>
  </table>
</div>
</fieldset>
<% end %>