config/routes.rb
DealHound::Application.routes.draw do

  root :to => 'commodities#index'
  controller :subscriptions do
    post 'subscription'
    get 'unsubscribe'
  end
  resources :commodities do
    member do
      get 'delete_img' => :del_image
    end
  end

  resources :deals do
    collection do
      post 'index'
      get 'show_commodities'
    end
  end
  resources :admins
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :delete
  end
  controller :categories do
    post 'edit_delete'
  end

  resources :users do
    member do
      get :edit_password
      put :save_password
      put :save_after_forget
    end
    collection do
      post :forget_password
      get :change_password
    end
  end
  resources :categories do
    resources :commodities, :only => [:index]
  end

  resources :vouchers
  resources :carts
  resources :line_items
  resources :orders

    

    

      

    

  

end

app/models/commodity.rb
class Commodity < ActiveRecord::Base

  attr_accessible :title, :features, :description, :vendor, :voucher, 
                  :images_attributes, :commodity_skus_attributes

  TYPE = { "Product" => 0, "Service" => 1 }

  #Validation
  validates :title, :presence => true
  validates :title, :allow_blank => true, :uniqueness => true
  
  #Category Association
  belongs_to :category

  #Vouchers Association
  has_many :vouchers, :dependent => :delete_all, :inverse_of => :commodity
  
  #CommoditySku Association
  has_many :commodity_skus, :dependent => :delete_all, :inverse_of => :commodity
  accepts_nested_attributes_for :commodity_skus, :reject_if => lambda { |t| t['size'].empty? && t['color'].empty? && t['quantity'].empty? && t['selling_price'].empty? && t['actual_price'].empty?}

  #Images Association
  has_many :images, :as => :snapshot, :dependent => :destroy
  accepts_nested_attributes_for :images, :reject_if => lambda { |t| t['photo'].blank?}

  #Class Methods

  def self.search(params)
    if params[:search]
      where('title LIKE ?', "%#{params[:search]}%").paginate_commodity(params[:page])
    else
      scoped.paginate_commodity(params[:page])
    end
  end

  def self.new_launches(page_num)
    where('created_at >= ?', 3.days.ago.to_time).paginate_commodity(page_num)
  end

private
  def self.paginate_commodity(page_num)
    paginate page: page_num, per_page: 6
  end
end

app/controllers/commodities_controller.rb
class CommoditiesController < ApplicationController
  Rails.logger.info "in commodity_controller start"
  include CommodityHelper
  before_filter(:only => [:new, :create, :delete, :edit]) { |controller| controller.authorize(true) }
  Rails.logger.info "in commodity_controller after before_filter"
  
  def index
    Rails.logger.info "entering index action"
    # debugger
    @category = Category.find_by_id(params[:category_id])
    if @category
      @commodities = @category.commodities.search(params)
    elsif params[:new_launch]
      @commodities = Commodity.new_launches(params[:page])
    else
      @commodities = Commodity.search(params)
    end
    Rails.logger.info "exiting index action"
  end

  def new
    @category = Category.new
    @categories = category_list
    @commodity = Commodity.new
    @commodity.images.build
    @commodity_sku = @commodity.commodity_skus.build
  end

  def show
    @commodity = Commodity.find(params[:id])
    respond_to do |format|
      if @commodity
        format.js
        format.html
      else
        flash[:error] = "Invalid Commodity"
        format.html { redirect_to commodities_url }
      end
    end
  end

  def edit
    begin
      @commodity = Commodity.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Invalid Commodity"
      redirect_to commodities_url
    else
      @categories = category_list
      @category = Category.new
      params[:selected_category] = @commodity.category.name
      @commodity.images.build
      @commodity.commodity_skus.build
    end
  end

  def update
    @cat = Category.find_by_name(params[:commodity]["category"])
    params[:commodity].delete_if { |k,v| k == "category" }
    @commodity = Commodity.find(params[:id])
    @commodity.category = @cat
    if @commodity.update_attributes(params[:commodity])
      redirect_to commodities_url, notice: "Update successful"
    else
      @category = Category.new
      @categories = category_list
      render :edit
    end
  end

  def del_image
    Image.destroy(params[:image_id])
    redirect_to request.referrer, notice: "Image deleted"
  end
  
  def destroy
    @commodity = Commodity.find(params[:id])
    @commodity.destroy
    redirect_to commodities_path
  end
  
  def create
    @cat = Category.find_by_name(params[:commodity]["category"])
    params[:commodity].delete "category"
    @commodity = Commodity.new(params[:commodity])
    @commodity.category = @cat
    if @commodity.save
      redirect_to @commodity
    else
      @category = Category.new
      @categories = category_list
      render :new
    end
  end
end

app/helpers/commodity_helper.rb
module CommodityHelper
  
end

app/views/commodities/_commodities.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
  
  <h2 class="blue_white align_message"><%= @category ? @category.try(:name) : "STORE" %></h2>
  
  <ul class="thumbnails" style = "margin-top:10px">

    <% @commodities.each do |commodity| %>
      <li class="span4 product_highlight" style ="margin-left:10px">
        <div class="thumbnail" style ="width:300px;height:360px">
          <% if commodity.images[0] %>
            <%= image_tag commodity.images[0].photo.url(:small) %>
          <% else %>
            <img src="/assets/calender/no_image.png" style ="width:100px;height:100px"></img>
          <% end %>
          <h3 style="min-height:80px;"><%= commodity.title.truncate(20) %><br>
          <%= commodity.vendor %></h3>
          <p style ="min-height:100px"><%= truncate(commodity.features.gsub(/\n/, '<br />'), :length => 100).html_safe %></p>
          <p style="text-align:center">
            <% if session[:admin] %>    
              <%= link_to(edit_commodity_path(commodity), :class => "btn") do %>
                <i class="icon-pencil"></i>  Edit
              <% end %>
              <%= link_to(commodity, :method => :delete, data: {confirm: "Are you sure?" }, :class => "btn btn-danger") do %>
                <i class="icon-remove"></i>   Delete
              <% end %>
            <% end %>
            <%= link_to(commodity_url(commodity), :class => "btn btn-info buy_btn") do%>
              <i class="icon-ok"></i>  <%= find_user && find_user.admin ? "Show" : "Buy/Show" %>
            <% end %>
          </p>
        </div>
      </li>
    <% end %>
    </ul>
<p class = "paginate_p"><%= will_paginate @commodities, :class => "pagination apple_pagination zero_margin" %></p>

app/views/commodities/_form.html.erb
<fieldset>
  <legend>Add A new commodity</legend><br>
  <legend>First Add/select a new category</legend>
  <div id = "add">
    <%= render 'categories/form', :remote => true %>
  </div>
  <%= nested_form_for @commodity do |f| %>
    <div>
      <% if @commodity.errors.get(:category) %>
        <%= @commodity.errors.get(:category).join(', ') %>
      <% end %>
      <%= f.select :category, @categories, :selected => params[:selected_category] %>
      <span><img id = "add_cat" src = "/assets/plus.png"/> (add a new category)</span>
    </div>
    <br>
    <fieldset class = "sub_fieldset">
      <legend>Details:</legend>
      <table class = "commodity">
        <tr>
          <td>
            <%= f.label :title, 'Name' %>
          </td>
          <td>
            <%= f.text_field :title %>
            <% if @commodity.errors.get(:title) %>
              <div class = "field_with_errors"><%= @commodity.errors.get(:title).first %></div>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.label :features, 'Features' %>
          </td>
          <td>
            <%= f.text_area :features %>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.label :vendor, 'Vendor' %>
          </td>
          <td>
            <%= f.text_field :vendor %>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.label :voucher, 'Type' %>
          </td>
          <td>
            <%= f.select :voucher, Commodity::TYPE %>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.label :description, 'Description' %>
          </td>
          <td>
            <%= f.text_area :description %>
          </td>
        </tr>
      </table>
    </fieldset>
    <br>
    <fieldset class = "sub_fieldset">
      <legend>Image Files</legend>
        <% if @commodity.errors.messages[ :"images.photo_content_type"] %>
          <div class = "field_with_errors"><%= @commodity.errors.messages[ :"images.photo_content_type"].first %></div>
          <br><br>
        <% end %>
        <%= f.fields_for :images, :html => { :multipart => true } do |img_f| %>
          <% if img_f.object.new_record? %>
            <%= img_f.file_field :photo %>
            <%= img_f.link_to_remove "Remove this image" %>
          <% else %>
            <%= image_tag img_f.object.photo.url(:small) %>
            <%= link_to "Remove this image", delete_img_commodity_url( { :image_id => img_f.object.id } ) %>
          <% end %>
          <br>
        <% end %>
        <br>
        <%= f.link_to_add "Add a image", :images %>
    </fieldset><br>
    <fieldset class = "sub_fieldset">
      <div>
      <% if @commodity.errors.messages[:"commodity_skus.quantity"] %>
        <div class = "field_with_errors">
          <%= @commodity.errors.messages[:"commodity_skus.quantity"].first%>
        </div>
      <% end %>
      <% if @commodity.errors.messages[:"commodity_skus.size"] %>
        <div class = "field_with_errors">
          <%= @commodity.errors.messages[:"commodity_skus.size"].first%>
        </div>
      <% end %>
      <% if @commodity.errors.messages[:"commodity_skus.actual_price"] %>
        <div class = "field_with_errors">
          <%= @commodity.errors.messages[:"commodity_skus.actual_price"].first %>
        </div>
      <% end %>
      <% if @commodity.errors.messages[:"commodity_skus.selling_price"] %>
        <div class = "field_with_errors">
          <%= @commodity.errors.messages[:"commodity_skus.selling_price"].first %>
        </div>
      <% end %>
      <div>
      <br><br>
      <%= f.fields_for :commodity_skus do |sku_f| %>      
        <legend>Type</legend>
        <table>
          <tr>
            <td>
              <%= sku_f.label :size, 'Size' %>
            </td>
            <td>
              <%= sku_f.text_field :size %>
            </td>
          </tr>
          <tr>
            <td>
              <%= sku_f.label :color, 'Color' %>
            </td>
            <td>
              <%= sku_f.text_field :color %>
            </td>
          </tr>
          <tr>
            <td>
              <%= sku_f.label :quantity, 'Quantity' %>
            </td>
            <td>
              <%= sku_f.text_field :quantity %>
            </td>
          </tr>
          <tr>
          <td>
            <%= sku_f.label :actual_price, 'Actual Price' %>
          </td>
          <td>
            <%= sku_f.text_field :actual_price %>
          </td>
        </tr>
        <tr>
          <td>
            <%= sku_f.label :selling_price, 'Selling Price' %>
          </td>
          <td>
            <%= sku_f.text_field :selling_price %>
          </td>
        </tr>
          <tr><td></td><td><%= sku_f.link_to_remove "Remove this type" %>
        </table>
      <% end %>
      <br>
      <%= f.link_to_add "Add a type", :commodity_skus %>
    </fieldset>
    
    <%= f.submit 'Submit' %>
  <% end %>
</fieldset>

app/views/commodities/_side_bar.html.erb
<%= link_to 'Home', commodities_url %>
<br>
<span><b>Categories:</b></span>
<ul id = "category">
  <% Category.all.each do |category| %>
  <li>
    <%= link_to category.name, category_commodities_url(category) %>
  </li>
  <% end %>
  <li>
    <%= link_to 'New Launches', commodities_url(new_launch: true) %>
  </li>
  <li>
    <%= form_tag deals_url, :class => "form-horizontal" do %>
    <div class = "control-group">
      City:
      <div class="controls zero_margin">
         <%= select_tag :city, options_for_select(Deal.select('Distinct city').order('city').map { |d| d.city}, session[:city]) %><br/>
        <%= submit_tag 'Deals', :class => "btn" %>
      </div>
    </div>
    <% end %>
  </li>

</ul>

app/views/commodities/index.html.erb
<%= form_tag commodities_path, :method => :get, :class => "search_ajax" do %>
  <p class = "search_p">
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, :class => "btn" %>
  </p>
  <div class = "sort_paginate_ajax"><%= render 'commodities' %></div>
<% end %>

<%#= "Espa&ntilde;ol &lt;br /&gt;".html_safe %>
<%#= '<br />'.html_safe %>
<%#= '1 <b>2</b>'.html_safe %>

app/views/commodities/index.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("commodities"))%>")

app/views/commodities/index.tablet.erb
<!DOCTYPE html>
<head>
  <title>Dealhound.com - Commodities</title>
  <meta name='viewport' content 'width=device-width, initial-scale=1'>
  <%= stylesheet_link_tag "jquery.mobile-1.3.0", 'jquery.mobile.structure-1.3.0', 'jquery.mobile.theme-1.3.0', :media => "all" %>
  <%= javascript_include_tag 'jquery', "jquery.mobile-1.3.0" %>
</head>
  <body>
    <div data-role="page" data-add-back-btn='true' data-back-btn-text='Home'>
      <div data-role="header" data-position='fixed'><h1>Commodities</h1></div>
      <div data-role='content'>
        <ul data-role="listview" data-inset="true">
          <li><a href="#iphone">Iphone</a></li>
          <li><a href="#htc">Htc</a></li>
          <li><a href="#sony">Sony Ericsson</a></li>
        </ul>
      </div>
      <div data-role='footer' data-position='fixed'>
        <h1><i>&copy; Nakshay Corp 2008</i></h1>
      </div>
    </div>
    <div data-role="page" id="htc" data-add-back-btn='true' data-back-btn-text='Back' data-fullscreen='true'>
      <div data-role="header" data-position='fixed'><h1>Htc</h1></div>
      <div data-role='content'>
        <img src="img/htc1.jpg">
      </div>
      <div data-role='footer' data-position='fixed'>
        <h1><i>&copy; Nakshay Corp 2008</i></h1>
      </div>
    </div>
    <div data-role="page" id="iphone" data-add-back-btn='true' data-back-btn-text='Back' data-fullscreen='true'>
      <div data-role="header" data-position='fixed'><h1>Htc</h1></div>
      <div data-role='content'>
        <img src="img/iphn1.jpg">
      </div>
      <div data-role='footer' data-position='fixed'>
        <h1><i>&copy; Nakshay Corp 2008</i></h1>
      </div>
    </div>
    <div data-role="page" id="sony" data-add-back-btn='true' data-back-btn-text='Back' data-fullscreen='true'>
      <div data-role="header" data-position='fixed'><h1>Htc</h1></div>
      <div data-role='content'>
        <img src="img/images.jpg">
      </div>
      <div data-role='footer' data-position='fixed'>
        <h1><i>&copy; Nakshay Corp 2008</i></h1>
      </div>
    </div>
  </body>
</html>

app/views/commodities/new.html.erb
<%= render 'commodities/form' %>

app/views/commodities/show.html.erb
<% user = find_user %>
<div>
  <div id ="show_left">
    <table id = "show_commodity">
      <tr>
        <td>
          <h2><%= @commodity.title %></h2>
        </td>
      </tr>
      <tr>
        <td> (By <%= @commodity.vendor.capitalize %>)</td>
      </tr>
      <tr>
        <td>
          <table id = "buy_at_show">
            <tr>
              <th>Deals</th>
              <td colspan = 5><span class = "buy_details">*Select Quantity, and click Buy</span></td>
            </tr>
            <% @commodity.commodity_skus.each do |sku| %>
            <tr>
              <%= form_tag line_items_path( :p_and_s => { id: sku, type: "CommoditySku" }) do %>
                <td class = "deal_column">
                  <% deal = sku.deals.where('visible = ?', true).first %>
                  <% if deal %>  
                    Time left:
                      <% time = Time.at(deal.end_date.to_time - Time.now).gmtime%>
                      <span id = "timer_d"><%= time.strftime("%d") %></span>D
                      <span id = "timer_h"><%= time.strftime("%H") %></span>H
                      <span id = "timer_m"><%= time.strftime("%M") %></span>M
                      <span id = "timer_s"><%= time.strftime("%S") %></span>S<br>
                    Price: &#8377; <%= selling_price = sku.selling_price %><br>
                    <b>Discount: <%= deal.discount %>%<br>
                    New Price: &#8377; <%= (1-(deal.discount/100)) * selling_price %></b>
                  <% end %>
                </td>            
                <% if sku.quantity > 0 %>
                  <td>
                    <%= select_tag :quantity, options_for_select((1..sku.quantity).to_a) %>
                  </td>
                <% end %>            
                <% unless sku.size.blank? %>
                  <td>
                    <%= sku.size %>
                  </td>
                <% end %>
                <td>
                <% if sku.actual_price %>
                <span id = "actual_price">&#8377; <%= sku.actual_price %></span>
                <% end %>
                <% if sku.selling_price %><br>
                <span id = "selling_price">&#8377; <%= sku.selling_price %></span>
                <% end %>
                </td>
                <% unless sku.color.blank? %>
                  <td>
                    <%= sku.color %>
                  </td>
                <% end %>
                <% unless user && user.admin %>
                  <% if sku.selling_price && sku.quantity > 0 %>
                    <td>
                      <%= submit_tag 'BUY' %>
                    </td>
                  <% else %>
                    <td>
                      Sold Out
                    </td>
                  <% end %>
                <% end %>
              <% end %>
            </tr>
            <% end %>
            <% @commodity.vouchers.each do |voucher| %>
            <tr>
              <%= form_tag line_items_path(:p_and_s => { id: voucher, type: "Voucher" }) do %>
                <td class = "deal_column">
                  <% deal = voucher.deals.where('visible = ?', true).first %>
                  <% if deal %>
                    Time left:
                      <% time = Time.at(deal.end_date.to_time - Time.now).gmtime%>
                      <span id = "timer_d"><%= time.strftime("%d") %></span>D
                      <span id = "timer_h"><%= time.strftime("%H") %></span>H
                      <span id = "timer_m"><%= time.strftime("%M") %></span>M
                      <span id = "timer_s"><%= time.strftime("%S") %></span>S<br>
                    Price: &#8377; <%= selling_price = voucher.selling_price %><br>
                    <b>Discount: <%= deal.discount %>%<br>
                    New Price: &#8377; <%= (1-(deal.discount/100)) * selling_price %></b>
                  <% end %>
                </td>
                <% if voucher.quantity > 0 %>
                  <td>
                    <%= select_tag :quantity, options_for_select((1..voucher.quantity).to_a) %>
                  </td>
                <% end %>
                <td>
                <% if voucher.selling_price && voucher.quantity > 0 %><br>
                <span id = "selling_price">&#8377; <%= voucher.selling_price %></span>
                <% end %>
                </td>
                <% unless user && user.admin %> 
                <% if voucher.selling_price %>
                    <td>
                      <%= submit_tag 'BUY' %>
                    </td>
                  <% end %>
                <% end %>
              <% end %>
            </tr>
            <% end %>
          </table>
        </td>
      </tr>
      <tr>
        <td><br><b>Features:</b> </td>
      </tr>
      <tr>
        <td colspan = 2>
          <% @commodity.features.split("\n").each do |feature| %>
          <%= feature %><br><br>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>

        </td>              
      </tr>
    </table>
  </div>
  <div id = "side_show">
    <div id = "slideshow">
      <% @commodity.images.each do |img| %>
      <%= image_tag img.photo.url(:small) %>
      <% end %>
    </div>
    <br>
    <br>
    <br>
    <% if user && user.admin %>
      <%= link_to 'Edit', edit_commodity_path(@commodity) %>
      <%= link_to 'Delete', @commodity, :method => :delete, data: {confirm: "Are you sure?" } %>
    <% end %>
    <%= link_to 'Back', commodities_path %>
  </div>
</div>
<% unless @commodity.description.blank? %>
<div id = "commodity_description">
  <hr>
  <h4>Description:</h4>
  <p><%= @commodity.description %></p>
</div>
<% end %>

app/views/commodities/show.js.erb
console.log("hello")
$('#timer').hide()